### ISSUE TITLE
Adding badges to the content

### ISSUE THREAD

**Issue by ajeetraina** [collabnix/docker-aiml-stories#12]
### Discussed in https://github.com/collabnix/docker-aiml-stories/discussions/11

<div type='discussions-op-text'>

<sup>Originally posted by **ajeetraina** July 27, 2024</sup>
It would be great if we can add a badge to the newly added content</div>

**Comment by bricefotzo** [comment]
@ajeetraina, this one is closed by #10 right? Can be closed?

**Comment by collabnix** [comment]
Yes, we can close this.
